# Generated by Django 5.1.7 on 2025-03-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_keys', models.JSONField(default=list)),
                ('host', models.CharField(default='', max_length=255)),
                ('baud_rate', models.IntegerField(default=9600)),
                ('serial_port', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Application Configuration',
                'verbose_name_plural': 'Application Configurations',
            },
        ),
    ]
